version: '3.5'
services:
  frontend:
    image: docker_test/frontend
    command: npm run serve
    build:
      context: ./
      dockerfile: frontend.dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
  backend:
    image: docker_test/backend
    command: ruby sinatra.rb
    build:
      context: ./
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "4567:4567"